blog/mysite/blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    # представление поста
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    # path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('<int:post_id>/comment/', views.post_comment, name='post_comment'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),
]

blog/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap


sitemaps = {
    'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace='blog')),
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap')
]

blog/mysite/blog/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager


# Create your models here.


class PublishedManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    class Status(models.TextChoices):
        DRAFT = 'DF', 'Draft'
        PUBLISHED = 'PB', 'Published'

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250,
                            unique_for_date='publish')
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='blog_posts')
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    update = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=2,
                              choices=Status.choices,
                              default=Status.DRAFT)
    tags = TaggableManager()

    objects = models.Manager()
    published = PublishedManager()

    class Meta:
        ordering = ['-publish']
        indexes = [models.Index(fields=['-publish'])]

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[self.publish.year,
                             self.publish.month,
                             self.publish.day,
                             self.slug])


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ['created']
        indexes = [
            models.Index(fields=['created']),
        ]

    def __str__(self):
        return f'Комментарий от {self.name}. Опубликован {self.post}'

blog/mysite/blog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body']


class SearchForm(forms.Form):
    query = forms.CharField()

blog/mysite/blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post, Comment
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.generic import ListView
from django.core.mail import send_mail, EmailMessage
from .forms import EmailPostForm, CommentForm, SearchForm
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
from django.views.decorators.http import require_POST
from django.contrib.postgres.search import TrigramSimilarity
from taggit.models import Tag
from django.db.models import Count


# Create your views here.


def post_list(request, tag_slug: str = None):
    post_published_list = Post.published.all()

    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        post_published_list = post_published_list.filter(tags__in=[tag])

    # Добавление пагинации по 3 поста на страницу
    paginator = Paginator(post_published_list, 3)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)

    return render(request, 'blog/post/list.html',
                  {
                      'posts': posts,
                      'tag': tag,
                  })


# class PostListView(ListView):
#     """
#     Альтернативный способ представления списка постов.
#     Аналог post_list
#     """
#
#     queryset = Post.published.all()
#     context_object_name = 'posts'
#     paginate_by = 3
#     template_name = 'blog/post/list.html'


def post_detail(request, year: int, month: int, day: int, post: str):
    post = get_object_or_404(Post,
                             status=Post.Status.PUBLISHED,
                             slug=post,
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)

    # Список активных комментариев к посту
    comments = post.comments.filter(active=True)
    # Форма для комментирования
    form = CommentForm()

    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags', '-publish')[:4]

    return render(request,
                  'blog/post/detail.html',
                  {
                      'post': post,
                      'comments': comments,
                      'form': form,
                      'similar_posts': similar_posts,
                  })


def post_share(request, post_id: int):
    # Извлекаю пост по id
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)

    sent = False

    if request.method == 'POST':
        # Форма передана на обработку
        form = EmailPostForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(post.get_absolute_url())

            subject = f'{cd["name"]} рекомендую прочитать {post.title}'
            message = (f'Прочитай {post.title} по ссылке {post_url}\n\n'
                       f'{cd["name"]} комментарии: {cd["comments"]}')

            send_mail(subject, message, 'igor.gass2003@mail.ru', [cd['to']])
            sent = True
    else:
        form = EmailPostForm()

    return render(request,
                  'blog/post/share.html',
                  {
                      'post': post,
                      'form': form,
                      'sent': sent,
                  })


@require_POST
def post_comment(request, post_id: int):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        # Создаю объект класса Comment, не сохраняя его в БД
        comment = form.save(commit=False)
        comment.post = post
        comment.save()

    return render(request,
                  'blog/post/comment.html',
                  {
                      'post': post,
                      'form': form,
                      'comment': comment,
                  })


def post_search(request):
    form = SearchForm()
    query = None
    results = []

    if 'query' in request.GET:
        form = SearchForm(request.GET)

        if form.is_valid():
            query = form.cleaned_data['query']
            # search_vector = SearchVector('title', weight='A') + SearchVector('body', weight='B')
            # search_query = SearchQuery(query)
            # search_query = SearchQuery(query, config='russian')  # Удаление стоп слов на русском (config)
            results = (Post.published.annotate(similarity=TrigramSimilarity('title', query))
                       .filter(similarity__gt=0.1).order_by('-similarity'))  # Поиск по триграммному сходству

    return render(request,
                  'blog/post/search.html',
                  {
                      'form': form,
                      'query': query,
                      'results': results,
                  })

blog/mysite/blog/templates/blog/post/comment.html
{% extends "blog/base.html" %}

{% block title %}
    Добавить комментарий
{% endblock %}

{% block content %}
    {% if comment %}
        <h2>Ваш коммент был добавлен</h2>
        <p>
            <a href="{{ post.get_absolute_url }}">Вернуться к посту</a>
        </p>
    {% else %}
        {% include "blog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock %}

blog/mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <h1>{{ post.title }}</h1>

    {% include "blog/post/includes/display_tags.html" %}

    <p class="date">
        Опубликован {{ post.publish }}. Автор: {{ post.author }}
    </p>
    {{ post.body|markdown }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Поделиться этим постом
        </a>
    </p>

    <h2>Похожие посты</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
        Пока нет похожих постов
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment {{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments</p>
    {% endfor %}
    {% include "blog/post/includes/comment_form.html" %}
{% endblock %}

blog/mysite/blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
    <li>
        <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    </li>
    {% endfor %}
</ul>

blog/mysite/blog/templates/blog/post/list.html
{% extends 'blog/base.html' %}
{% load blog_tags %}

{% block title %}Мой блог{% endblock %}

{% block content %}
    <h1>Мой блог</h1>
    {% if tag %}
        <h2>Посты с тегом "{{tag.name}}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>

        {% include "blog/post/includes/display_tags.html" %}

        <p class="date">
            Опубликован {{ post.publish }}. Автор: {{ post.author }}
        </p>
        {{ post.body|markdown|truncatewords_html:30 }}
    {% endfor %}
    {% include "pagination.html" with page=posts %}
{% endblock %}

blog/mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}

{% block title %}
    Поиск
{% endblock %}

{% block content %}
    {% if query %}
        <h1>Посты, содержащие "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Найдено {{ total_results }} постов{{ total_results|pluralize }}
            {% endwith %}
        </h3>

        {% for post in results %}
            <h4>
                <a href="{{ post.get_absolute_url }}">
                    {{ post.title }}
                </a>
            </h4>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>Нет результатов по вашему запросу</p>
        {% endfor %}

        <p>
            <a href="{% url 'blog:post_search' %}">Искать снова</a>
        </p>
    {% else %}
        <h1>Поиск по постам</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Поиск">
        </form>
    {% endif %}
{% endblock %}

blog/mysite/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}
    Поделиться постом
{% endblock %}

{% block content %}
    {% if sent %}
        <h1>Сообщение успешно отправлено</h1>
        <p>
            "{{ post.title }}" было успешно отправлено по адресу {{ form.cleaned_data.to }}
        </p>
    {% else %}
        <h1>Поделиться "{{post.title}}" по почте</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Отправить письмо">
        </form>
    {% endif %}
{% endblock %}